######################### Server #########################

server:
  port: ${SERVER_PORT:8091}

######################### Spring #########################

spring:

  servlet:
    multipart:
      enabled: true
      max-file-size: 500MB
      max-request-size: 515MB
      file-size-threshold: 2KB

  application:
    email-size-limit: 26214400
    temp-dir: ./attachments/temp
    storage-location: ./uploadedFiles
    email-address: our.wedding.story.pl@gmail.com

  datasource:
    url: ${MYSQL_DB_URL:jdbc:mysql://localhost:3306/weddings}
    password: ${MYSQL_DB_PASS:pass}
    username: ${MYSQL_DB_USERNAME:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:sql/schema-dev.sql
    data: classpath:sql/dev-initializer.sql
    hikari:
      maximum-pool-size: 30
      connection-timeout: 20000
      leak-detection-threshold: 25000
  jpa:
    # Uncomment for sql stats
    #    properties:
    #      hibernate:
    #        generate_statistics: true
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mail:
    host: smtp.gmail.com
    port: 587
    password: '{cipher}437aca0ff09e62d1ca4ad078a092b287543d60401577a72f294e79de15be6942b84437f86d05eda3d81cbb6a66be30c1'
    username: '{cipher}dfc5afcfdf4221c944040c2db9b8b274082868b54d114927ee20513138c747c7e2fc398724112b2e28b6ec2a743790af'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

######################### Actuator #########################

management:
  endpoint:
    health:
      show-details: always

######################### Logging #########################

logging:
  level:
    com.simonjoz: DEBUG

######################## JSON Web Token #########################

jwt:
  secretKey: sdfdskdsflsdfkjasfipqewouir231431324324dasd23asdasmcskjacloojfefcxcvbckvosfbuqwfvpeifw
  expirationTime: 36000000
