######################### Server #########################

server:
  port: ${SERVER_PORT:8080}

######################### Zuul #########################

zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie, Set-Cookie
  routes:

    wedding-api:
      path: /api/v1/**
      serviceId: wedding-api
      stripPrefix: false

    wedding-api-swagger:
      path: /swagger-ui.html/**
      serviceId: wedding-api
      stripPrefix: false

    api-actuator:
      path: /manage/wedd-api/**
      serviceId: wedding-api
      stripPrefix: false

    auth:
      path: /api/auth/**
      serviceId: wedding-api
      stripPrefix: false

#    web-admin:
#      path: /**
#      url: ${ADMIN_CLIENT_ULR:http://localhost:4200}

######################### Ribbon #########################

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 3000

wedding-api:
  ribbon:
    ReadTimeout: 240000
    ConnectTimeout: 60000

######################### Actuator #########################

management:
  endpoints:
    web:
      base-path: /manage/wedd-api
      exposure:
        include: "health, info, filters, routes, refresh, prometheus"
  endpoint:
    health:
      show-details: always

info:
  app:
    version: 1.0.0
    name: Zuul Gateway
    description: Gateway for Weeding Couples Manager App.


######################### Logging #########################

logging:
  level:
    com.sda: DEBUG
    com.netflix.config.sources.URLConfigurationSource: ERROR