######################### Server #########################

server:
  port: ${SERVER_PORT:8080}

######################### Zuul #########################

zuul:
  ignoredServices: '*'
  sensitiveHeaders: Cookie, Set-Cookie
  routes:

    wedd-api:
      path: /api/v1/**
      serviceId: wedd-api
      stripPrefix: false

    auth:
      path: /api/auth/**
      serviceId: wedding-api
      stripPrefix: false

    grafana:
      path: /grafana
      url: ${GRAFANA_URL}

    prometheus:
      path: /prometheus
      url: ${PROMETHEUS_URL}

#    frontend:
#      path: /**
#      url: ${ADMIN_CLIENT_URL:http://localhost:4200}


######################### Ribbon #########################

ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 3000

wedd-api:
  ribbon:
    ReadTimeout: 240000
    ConnectTimeout: 60000

######################### Actuator #########################

management:
  endpoints:
    web:
      base-path: ${ACTUATOR_BASE_PAHT:/manage}
      exposure:
        include: "health, info, filters, routes, refresh, prometheus"
  endpoint:
    health:
      show-details: always

info:
  app:
    version: 1.0.0
    name: Zuul Gateway
    description: Gateway for Weeding Couples Manager App.


######################### Logging #########################

logging:
  level:
    com.sda: DEBUG
    com.netflix.config.sources.URLConfigurationSource: ERROR