######################### Server #########################

server:
  port: ${SERVER_PORT:8091}

######################### Spring #########################

spring:

  application:
    temp-dir: ${TEMP_DIR_PATH}
    email-address: ${EMAIL_ADDRESS}
    storage-location: ${STORAGE_PATH}
    email-size-limit: ${EMAIL_SIZE_LIMIT}

  servlet:
    multipart:
      enabled: true
      max-file-size: ${MAX_UPLOAD_SZIE:500MB}
      max-request-size: ${MAX_REQEST_SZIE:510MB}
      file-size-threshold: 2KB

  datasource:
    url: ${POSTGRESQL_DB_URL}
    username: ${POSTGRESQL_DB_PASS}
    password: ${POSTGRESQL_DB_USERNAME}
    initialization-mode: never
    schema: classpath:sql/schema-prod.sql
    hikari:
      maximum-pool-size: 30
      connection-timeout: 20000
      leak-detection-threshold: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    password: ${EMAIL_PASS}
    username: ${EMAIL_ADDRES}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

######################### Actuator #########################

management:
  endpoint:
    health:
      show-details: when_authorized

######################### Logging #########################

logging:
  level:
    com.simonjoz: ${LOG_LEVEL:DEBUG}

######################## JSON Web Token #########################
jwt:
  expirationTime: ${JWT_EXP_TIME:36000000}
  secretKey: ${JWT_SECRET:240792###incradibly__Secret#$Api;;KEY;;fasdfsfasqQWECHES$#%$%#$^$^$%^#!@#!*^*^&(*\S??>}
