######################### Server #########################

server:
  compression:
    enabled: true
    min-response-size: 2048  # default
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript,
      application/javascript, application/json, application/xml  #default

######################### Spring #########################
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml

######################### Actuator #########################

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus, refresh, httptrace"
      base-path: /manage

  endpoint:
    health:
      show-details: always

info:
  app:
    version: 1.0.0
    name: Weddings API
    description: API for managing informations about wedding couples.

######################### Gateway #########################

gateway:
  url: ${GATEWAY_URL:http://localhost:8080}

######################### Logging #########################

logging:
  level:
    com.netflix.config.sources.URLConfigurationSource: ERROR
