######################### Server #########################

server:
  compression:
    enabled: true
    min-response-size: 2048  # default
    mime-types: text/html, text/xml, text/plain, text/css, text/javascript,
      application/javascript, application/json, application/xml  #default

######################### Spring #########################
spring:
  cache:
    jcache:
      config: classpath:ehcache.xml

######################### Actuator #########################

management:
  endpoints:
    web:
      exposure:
        include: "health, info, prometheus, refresh, httptrace"
      base-path: ${ACTUATOR_BASE_PAHT:/manage}

  endpoint:
    health:
      show-details: always

info:
  app:
    version: 1.0.0
    name: Weddings API
    description: API for managing informations about wedding couples.
